language: node_js

node_js:
  - "0.10"

sudo: false
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

before_script:
  - sleep 15
  - mongo --version
  - ./clean.sh
  - mongo test --eval 'db.createUser({ user: "tester", pwd: "test", roles: [{ role: "readWrite", db: "test" }]})'
