language: node_js

node_js:
  - "0.10"

services:
  - mongodb

before_script:
  - sleep 15
  - mongod --version
  - mongorestore --db test spec/e2e/fixtures/db
  - mongo test --eval 'db.addUser("tester", "test");'
