language: node_js

node_js:
  - "4"
  - "5"
  - "6"

sudo: false
services:
  - mongodb

before_script:
  - sleep 15
  - mongo --version

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8